version: 2

project_name: imsg

changelog:
  disable: true

builds:
  - id: imsg
    main: ./cmd/imsg
    binary: imsg
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - builds:
      - imsg
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt
